# -*- coding: utf-8 -*-
"""ml_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N13wwQmfJLmEFRDtK43gO3Oq9HjpFsKJ
"""

import zipfile
zip_ref=zipfile.ZipFile('/content/archive.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

import numpy as np
import pandas as pd

df=pd.read_csv("/content/collegePlacement_data_10000_rows.csv")

df.head()

df=df[['Internships','CGPA','HistoryOfBacklogs','PlacedOrNot']]

df.head()

#steps
#preprocess=eda+feature selection
#extract input and output cols
#scale the values
#train the split
#train the model
#evaluate the model/model selection
#deploy the model

df.info

df.info()

import matplotlib.pyplot as plt

plt.scatter(df['CGPA'],df['Internships'],df['HistoryOfBacklogs'])

plt.scatter(df['CGPA'],df['Internships'],c=df['PlacedOrNot'])

x=df.iloc[:,0:2]
y=df.iloc[:,-1]

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

x_train

x_test=scaler.transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

#model training
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train,y_train.values,clf=clf,legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))

